#!/bin/bash

CONFIG_CHECK_JAR=~/Documents/java-checkstyle/checkstyle.jar;
CONFIG_CHECK_FILE=~/Documents/java-checkstyle/checkstyle.xml;
CONFIG_ERROR_FILE=~/Documents/java-checkstyle/checkstyle_errors.xml;
CONFIG_ERROR_REPORT_FILE=~/Documents/java-checkstyle/checkstyle_report.xml;

config=1;
if [ ! -f $CONFIG_CHECK_JAR ]
then
  config=0;
  echo "Please confirm checkstyle jar, path: $CONFIG_CHECK_JAR ";
  
fi

if [ ! -f $CONFIG_CHECK_FILE ]
then
  echo "Please confirm checkstyle file, path: $CONFIG_CHECK_FILE ";
  config=0;
fi


if [ "$config" = 0 ]
then
  echo "config error!";
  exit -1;
fi

javafiles=`git diff --cached --name-only |grep '\.java'`
#echo $javafiles

if [ -f $CONFIG_ERROR_FILE ]
then
  rm $CONFIG_ERROR_FILE
fi

JAVA_CMD="java -cp $CONFIG_CHECK_JAR com.puppycrawl.tools.checkstyle.Main -c $CONFIG_CHECK_FILE $javafiles -f xml -o $CONFIG_ERROR_FILE"
#echo $JAVA_CMD
$JAVA_CMD

if [ ! -f $CONFIG_ERROR_FILE ]
then
  exit 0
fi

response=`cat $CONFIG_ERROR_FILE|grep \<error|head -n 1`;
if [[ $response == *"error"* ]]
then
  awk '{print;} NR == 1 { print "<?xml-stylesheet xmlns=\"http://www.w3.org/1999/xhtml\" href=\"checkstyle-simple.xsl\" type=\"text/xsl\"?>"}' $CONFIG_ERROR_FILE > $CONFIG_ERROR_REPORT_FILE;
  echo "Check your code. Open by Safari or Chrome ( --allow-file-access-from-files ): $CONFIG_ERROR_REPORT_FILE";
  open $CONFIG_ERROR_REPORT_FILE
  exit -1
else
  #echo "commit successful!"
  exit 0 
fi
